### PR TITLE
Spiral staircase brush improvements + bug fix

### LINKED ISSUE #80: Add more stair types to the spiral staircase brush
**Idea from @Aurelien30000:** Rewrite ``SpiralStaircaseBrush``.

_- Add an arg to pass the width of the staircase. Voxel height is the default implemented arg for several brushes._
_- Accept all stairs and steps._

_Originally posted by @Aurelien30000 in https://github.com/IntellectualSites/FastAsyncVoxelSniper/discussions/52#discussioncomment-1248423_

### LINKED ISSUE #168: Fill Down Brush Problem
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

Similar to the splatter disc issue before, the fill-down command does not fill below the height of 0.

### To Reproduce

1. /b fd
2. use any material
3. right-click on any heights above zero

### Expected behaviour

it should fill blocks down with the desired material until it intersects another block

### Screenshots / Videos

_No response_

### Error log (if applicable)

_No response_

### Favs Debugpaste

https://athion.net/ISPaster/paste/view/757d4e1791e4407fbaf2a5d12023ffc7

### Favs Version

FastAsyncVoxelSniper version 2.3.2

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://dev.bukkit.org/projects/favs and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Aurelien30000**
## Overview

Fixes #168
Fixes #80

## Description

- Fixes fill-down brush below 0 by using min height of the editsession.

- Gets rid of former brush usage with stone/wood stair type. Adds support for all slabs and stairs. Uses ``BlockCategories`` to determine the stair type and the build logic to use.

## Submitter Checklist

- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] New public fields and methods are annotated with `@since TODO`.
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: src/main/java/com/thevoxelbox/voxelsniper/brush/type/SpiralStaircaseBrush.java [hunk 1]
```diff
@@ -2,32 +2,36 @@
...
 import java.util.stream.Stream;
 
 public class SpiralStaircaseBrush extends AbstractBrush {
 
-    private static final String DEFAULT_STAIR_TYPE = "block";
     private static final String DEFAULT_SDIRECT = "c";
     private static final String DEFAULT_SOPEN = "n";
 
-    private String stairType; // "block" 1x1 blocks (default), "step" alternating step double step, "stair" staircase with blocks on corners
+    private static final List<String> STAIR_TYPES = Arrays.stream(StairType.values())
```
Comment (NotMyFault) [inline src/main/java/com/thevoxelbox/voxelsniper/brush/type/SpiralStaircaseBrush.java]: What exactly is that used for, because it's not used at all.

File: src/main/java/com/thevoxelbox/voxelsniper/brush/type/SpiralStaircaseBrush.java [hunk 2]
```diff
@@ -72,33 +72,47 @@ public List<String> handleCompletions(String[] parameters, Snipe snipe) {
...
     @Override
     public void handleGunpowderAction(Snipe snipe) {
         BlockVector3 lastBlock = getLastBlock();
-        buildStairWell(snipe, lastBlock); // make stairwell above target
+        buildStairWell(snipe, lastBlock, getStairType(snipe)); // make stairwell above target
+    }
+
+    /**
+     * @since 2.4.1
+     */
```
Comment (NotMyFault) [inline src/main/java/com/thevoxelbox/voxelsniper/brush/type/SpiralStaircaseBrush.java]: I'm fine with `@since TODO` on public fields, otherwise use a todo placeholder here if you want to add them too.

File: src/main/java/com/thevoxelbox/voxelsniper/brush/type/SpiralStaircaseBrush.java [hunk 3]
```diff
@@ -72,33 +72,47 @@ public List<String> handleCompletions(String[] parameters, Snipe snipe) {
...
+        }
+        if (Materials.isStair(blockType)) {
+            return StairType.STAIR;
+        }
+        return StairType.BLOCK;
     }
 
-    private void buildStairWell(Snipe snipe, BlockVector3 targetBlock) {
+    private void buildStairWell(Snipe snipe, BlockVector3 targetBlock, StairType stairType) {
         ToolkitProperties toolkitProperties = snipe.getToolkitProperties();
```
Comment (NotMyFault) [inline src/main/java/com/thevoxelbox/voxelsniper/brush/type/SpiralStaircaseBrush.java:88]: It would probably make sense to refactor this into a private method, it shares the same ~50 lines like #digStairWell

File: src/main/java/com/thevoxelbox/voxelsniper/brush/type/SpiralStaircaseBrush.java [hunk 4]
```diff
@@ -276,76 +290,64 @@ private void buildStairWell(Snipe snipe, BlockVector3 targetBlock) {
...
+                                            newState.getDefaultState().with(
+                                                    PropertyKey.TYPE,
+                                                    "top"
+                                            )
                             );
                         }
                     } else if (spiral[x][i][z] == 2) {
-                        if (this.stairType.equalsIgnoreCase("step")) {
-                            setBlockData(position, BlockTypes.OAK_SLAB.getDefaultState().with(PropertyKey.TYPE, "double"));
+                        if (stairType == StairType.STEP) {
```
Comment (NotMyFault) [inline src/main/java/com/thevoxelbox/voxelsniper/brush/type/SpiralStaircaseBrush.java]: See my comment above.

File: src/main/java/com/thevoxelbox/voxelsniper/brush/type/SpiralStaircaseBrush.java [hunk 5]
```diff
@@ -609,9 +588,28 @@ public void sendInfo(Snipe snipe) {
...
         messenger.sendBlockDataMessage();
-        messenger.sendMessage(ChatColor.BLUE + "Staircase type: " + this.stairType);
+        messenger.sendMessage(ChatColor.BLUE + "Staircase type: " + getStairType(snipe).getName());
         messenger.sendMessage(ChatColor.BLUE + "Staircase turns: " + this.sdirect);
         messenger.sendMessage(ChatColor.BLUE + "Staircase opens: " + this.sopen);
     }
 
+    /**
+     * @since 2.4.1
+     */
```
Comment (NotMyFault) [inline src/main/java/com/thevoxelbox/voxelsniper/brush/type/SpiralStaircaseBrush.java]: See my since commend above.

File: src/main/java/com/thevoxelbox/voxelsniper/util/material/Materials.java [hunk 6]
```diff
@@ -16,4 +17,18 @@ public static boolean isLiquid(BlockType blockType) {
...
+     */
+    public static boolean isSlab(BlockType blockType) {
+        return BlockCategories.SLABS.contains(blockType);
+    }
+
+    /**
+     * @since 2.4.1
+     */
+    public static boolean isStair(BlockType blockType) {
+        return BlockCategories.STAIRS.contains(blockType);
```
Comment (NotMyFault) [inline src/main/java/com/thevoxelbox/voxelsniper/util/material/Materials.java]: That should be `since TODO` and wrapped into the appropriate javadocs.

File: src/main/java/com/thevoxelbox/voxelsniper/brush/type/SpiralStaircaseBrush.java (hunk 1 above)
Comment (Aurelien30000) [reply src/main/java/com/thevoxelbox/voxelsniper/brush/type/SpiralStaircaseBrush.java]: Oops, thanks!

File: src/main/java/com/thevoxelbox/voxelsniper/brush/type/SpiralStaircaseBrush.java (hunk 3 above)
Comment (Aurelien30000) [reply src/main/java/com/thevoxelbox/voxelsniper/brush/type/SpiralStaircaseBrush.java:88]: Makes sense ;)

**Review by NotMyFault — APPROVED** [review]
Thanks for your contribution!
