### PR TITLE
 [CLOUD Beta] Fix performer commands

### LINKED ISSUE #317: Performer Issue on Snapshot-3.0.0
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

While trying to use FAVS I am unable to use performers. 

On 2.9.4 using the "/performer mm" works properly.

However on Snapshop-3.0.0 they return: 

(Fav) An unexpected error occurred.

I've tried a couple different variations such as mm or mat-mat to be sure. (Please add "/performer" command to the wiki)

### To Reproduce

Try to use the performer command. 

/b b

/b 10

/performer mm

### Expected behaviour

I expect that after I used the "/performer mm" command that I was going to select dirt as my replaceVoxel and air as my Voxel. 

### Screenshots / Videos

_No response_

### Error log (if applicable)

https://paste.gg/p/anonymous/aedfba6671c54722b88314065f19f5ac

### Favs Debugpaste

https://athion.net/ISPaster/paste/view/8f74e29b754f4721bec91553328a42e5

### Favs Version

Snapshot 3.0.0

### Checklist

- [X] I have included a debugpaste.
- [X] I am using the newest build from https://dev.bukkit.org/projects/favs and the issue still persists.

### Anything else?

Thanks for creating and maintain one of my most favorite plugins. C:

### PR DESCRIPTION
**Pull request by Aurelien30000**
## Overview

Fixes #317

## Description

- Fix the logic according to the custom command executor.

```[tasklist]
### Submitter Checklist
- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] New public fields and methods are annotated with `@since TODO`.
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).
```

### CODE REVIEW

File: src/main/java/com/thevoxelbox/voxelsniper/performer/type/combo/ComboComboNoPhysicsPerformer.java [hunk 1]
```diff
@@ -19,10 +21,9 @@ public class ComboComboNoPhysicsPerformer extends AbstractPerformer {
 
     @CommandMethod("")
```
Comment (OneLiteFeather) [inline src/main/java/com/thevoxelbox/voxelsniper/performer/type/combo/ComboComboNoPhysicsPerformer.java:22]: I might be wrong. Do you need that here?

Comment (Aurelien30000) [reply src/main/java/com/thevoxelbox/voxelsniper/performer/type/combo/ComboComboNoPhysicsPerformer.java:22]: It's fine, it means "no addition" to the global class command annotation above ``performer|perf|p combo-combo-nophys|ccp``. This corresponds to the handler for the ``CommandMethod`` declared on the class, it acts as a prefix for internal ``CommandMethod``.

**Review by OneLiteFeather — APPROVED** [review]
LGTM

**Review by NotMyFault — APPROVED** [review]
